on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
        - name: Install MinGW
          uses: egor-tensin/setup-mingw@v2.2.0
        - uses: actions/checkout@v3
        - name: Set up Cygwin
          uses: egor-tensin/setup-cygwin@v4
          with:
            packages: cmake gcc-g++ libtool bintools automake make
        - run: |
          # This is a real bash script!
          basic() {
              ls -Al
              pwd
          }
          basic
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
