on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
        - name: Install MinGW
          uses: egor-tensin/setup-mingw@v2.2.0
        - uses: actions/checkout@v3
        - name: configure and make 
          run: |
            ls

